spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC


##<----------h2------------>
#spring:
#  datasource:
##    url: jdbc:h2:file:~/h2/userApiValidationAndException
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  profiles:
#    active: default
#
#
#---
#
#spring:
#  profiles: default
#
#doge:
#  wow: 10
#  such: so
#  very: true
#
#---
#
#spring:
#  profiles: unit-test
#
#doge:
#  wow: 4
